name: Build DesktopApp

on:
  push:
    branches: [ master, main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    env:
      CONFIG: Release
      PROJECT: DesktopApp/DesktopApp.csproj
      FRAMEWORK: net9.0-windows
      APP_NAME: iptv-desktop-browser
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
          cache: true

      - name: Restore
        run: dotnet restore $env:PROJECT

      - name: Build (framework-dependent)
        run: dotnet build $env:PROJECT -c $env:CONFIG -f $env:FRAMEWORK --no-restore

      - name: Publish (self-contained win-x64)
        run: >-
          dotnet publish $env:PROJECT -c $env:CONFIG -f $env:FRAMEWORK
          -r win-x64 --self-contained true /p:PublishSingleFile=true /p:PublishTrimmed=false
          -o publish/win-x64-self

      - name: Publish (framework-dependent win-x64)
        run: >-
          dotnet publish $env:PROJECT -c $env:CONFIG -f $env:FRAMEWORK
          -r win-x64 --self-contained false /p:PublishSingleFile=false
          -o publish/win-x64-fdd

      - name: Zip artifacts
        run: |
          Compress-Archive -Path publish/win-x64-self/* -DestinationPath $env:APP_NAME-self-contained-win-x64.zip
          Compress-Archive -Path publish/win-x64-fdd/* -DestinationPath $env:APP_NAME-framework-dependent-win-x64.zip

      - name: Upload self-contained artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${ { env.APP_NAME } }-self-contained-win-x64
          path: ${{ env.APP_NAME }}-self-contained-win-x64.zip
          if-no-files-found: error

      - name: Upload framework-dependent artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${ { env.APP_NAME } }-framework-dependent-win-x64
          path: ${{ env.APP_NAME }}-framework-dependent-win-x64.zip
          if-no-files-found: error

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/**/iptv-desktop-browser-self-contained-win-x64.zip
            dist/**/iptv-desktop-browser-framework-dependent-win-x64.zip
          draft: false
          prerelease: ${{ contains(github.ref_name, '-rc') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-alpha') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
