name: Build DesktopApp

permissions:
  contents: write

on:
  push:
    branches: [ master, main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    env:
      CONFIG: Release
      PROJECT: DesktopApp/DesktopApp.csproj
      FRAMEWORK: net9.0-windows
      APP_NAME: iptv-desktop-browser
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
            dotnet-version: '9.0.x'
            cache: true
            cache-dependency-path: |
              DesktopApp/packages.lock.json

      - name: Restore
        run: dotnet restore $env:PROJECT

      - name: Verify lock file
        run: |
          if (-not (Test-Path "DesktopApp/packages.lock.json")) { Write-Error 'packages.lock.json missing'; exit 1 }

      - name: Publish single-file self-contained (win-x64)
        run: >-
          dotnet publish $env:PROJECT -c $env:CONFIG -f $env:FRAMEWORK -r win-x64 --self-contained true
          /p:PublishSingleFile=true /p:EnableCompressionInSingleFile=true /p:PublishTrimmed=false /p:DebugType=None
          -o publish/self

      - name: List publish output
        run: dir publish/self

      - name: Normalize executable name
        shell: pwsh
        run: |
          $exe = Get-ChildItem publish/self -Filter *.exe | Select-Object -First 1
          if (-not $exe) { Write-Error 'No exe produced'; exit 1 }
          Rename-Item $exe.FullName "$($exe.DirectoryName)/$env:APP_NAME.exe"
          dir publish/self

      - name: Upload executable artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.APP_NAME }}-win-x64
          path: publish/self/${{ env.APP_NAME }}.exe
          if-no-files-found: error

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: iptv-desktop-browser-win-x64
          path: dist
      - name: Show files
        run: dir dist
      - name: Create Release (single exe)
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/iptv-desktop-browser.exe
          draft: false
          prerelease: ${{ contains(github.ref_name, '-rc') || contains(github.ref_name, '-beta') || contains(github.ref_name, '-alpha') }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
